# site settings
title: Charles Vanchieri
subtitle: Portfolio
email: CVanchieri@gmail.com
description: “May your choices reflect your hopes, not your fears.”
baseurl: "/DSPortfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Charles Vanchieri
#street_address: 2503 Mardell Way
city: Randwick
state: NSW
zip_code: 94043
country: Australia
phone: (61)433854484

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
#facebook_url:
github_url: https://github.com/CVanchieri
#gitlab_url:
#googleplus_url:
instagram_url: https://www.instagram.com/cvanchieri6/
linkedin_url: https://www.linkedin.com/in/cvanchieri6/
#pinterest_url:
#slack_url:
twitter_url: https://twitter.com/CVanchieri6

# build settings
markdown: kramdown

sass:
  style: compressed
